### ISSUE TITLE
custom base path for static content

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/pixl-server-web#6]
Just to clarify, there is no any standard option alter base path ("/") for serving content from "http_htdocs_dir" directory? 

I see you can achive similar behavior by setting http_htdocs_dir to some dummy value, and then adding 
```js
this.web.addDirectoryHandler('/custom', '/path/to/htdosc/dir')
```
Would be a handy option just to disable serving static content on '/'. Currently if you don't specify http_htdocs_dir webserver will crash.
 Ideal behavior would be pushing "/custom" path from pixl-server config, then it would disable serving on "/" and set htdocs directory for /custom. Or instead of disabling - redirect "/" to "/custom", or just display welcome message specifying what custom path s used.

Same pixl-server base path config could be also respected by pixl-server-api component, and make base api uri to /custom/api ( vs api). This can be set separately in API configs, but would be easier to do both API and WEB in one shot

The reason for this issue - using those steps above I was able to serve cronicle on sub path (e.g. http://localhost:3012/cronicle), just with minimal tweaking on some absolute paths and socket.io config. This workaround is a bit cumbersome though, so would be really nice to have some top level config like base_path to achieve that.

**Comment by mikeTWC1984** [comment]
Interesting, just realized you can prefix any sub-path to /api, and it works same (in cronicle). E.g. below to path 

/api/app/get_history
/blah/blah/api/app/get_history

Is it by design? This is actually handy for this issue, no need to configure base_uri for API. I also realize you can add URI handler for / path to achieve what I needed.

**Comment by jhuckaby** [comment]
That was unintentional sloppiness on my part, specifically in pixl-server-api.  It's basically missing a `^` regexp character prefix in the default base URI match, but I'll leave it as is 😊

You should be aware of this, however:

https://github.com/jhuckaby/Cronicle/blob/ae28d63be2fe4b9498da686bdf1dcccbe8a47ad0/lib/engine.js#L99-L106

I can't remember exactly why I am injecting the server_groups array into every API request, but this little snippet of code DOES INDEED match on the start of the URI, so it won't run for `/blah/blah/api/app/get_history` and stuff.

Ah, I remember now, it's used to make sure users have access to specific groups, if they are limited:

https://github.com/jhuckaby/Cronicle/blob/master/lib/api.js#L376-L380

So this will require a change.

**Comment by jhuckaby** [comment]
Here you go, this should do the trick: https://github.com/jhuckaby/Cronicle/commit/48490e0d9a97245d2f75ade7546f34ff266f4f93
